Add opt support to funcs
Without this we can get the following error:

error: comparison operators cannot be chained
    --> src/src/lib.rs:2438:23
     |
2438 |                 Option<AzleInline2642418748796565738>::_ty(),
     |                       ^                             ^
     |
help: use `::<...>` instead of `<...>` to specify lifetime, type, or const arguments
     |
2438 |                 Option::<AzleInline2642418748796565738>::_ty(),
     |                       ++